### ISSUE TITLE
Installation scheitert

### ISSUE THREAD

**Issue by vore** [andynoack/snips_homematic_xml#1]
Hallo! 
Machen wir mal hier weiter (Vore76) .. die Kommentarfunktion im Snips AppStore ist nicht ideal.
Ich habe den Raspi noch einmal komplett neu aufgesetzt (aus anderen Gründen).
Also ein frisches Raspian.. bei der Installation des Assistenten erhalte ich jetzt die folgende Fehlermeldung:
`✖ Error setting up virtualenv, one or more actions might not be able to run. Reason :
Could not find a version that satisfies the requirement libxml2-python (from -r requirements.txt (line 7)) (from versions: )
No matching distribution found for libxml2-python (from -r requirements.txt (line 7))
`
Frage: wo und wie bekomme ich diese Library?

Gruß
Vore

**Comment by andynoack** [comment]
Vielen Dank für den Hinweis. Ich habe das entsprechende Paket entfernt, klappt es nun?
Alternative Lösung wäre, libxml2-dev mit apt im System zu installieren.

**Comment by vore** [comment]
Hallo!
Die Installation lief jetzt durch. Allerdings werden die Geräte nicht abgefragt und es gibt kein Datei "cache.txt". Im Syslog gibt es Einträge, dass die "URL" ein Problem hat. Wenn ich die URL aus der config.ini kopieren und im Browser einfüge, wird die XML-Api aufgerufen. 
Die URL passt also generell:

> [global]
url=http://192.168.11.2/addons/xmlapi/

Hier Auszüge aus dem Syslog (oben beim booten, unten beim Aufruf von "reload")

> Mar 16 08:22:14 raspberrypi snips-tts[516]: INFO:snips_tts_hermes: starting with provider PicoTts
Mar 16 08:22:14 raspberrypi snips-skill-server[523]: INFO:snips_skill_server_lib::runner: searching dir for actions: /var/lib/snips/skills/snips_homematic_xml
Mar 16 08:22:14 raspberrypi snips-audio-server[527]: INFO:snips_audio_server: Starting audio server on mqtt for site default
Mar 16 08:22:14 raspberrypi snips-audio-server[527]: INFO:snips_audio_server: Capture enabled: true, Playback enabled: true
Mar 16 08:22:14 raspberrypi snips-skill-server[523]: INFO:snips_skill_server_lib::runner: found action "/var/lib/snips/skills/snips_homematic_xml/action-executeProgram-Homematic.py"
Mar 16 08:22:14 raspberrypi snips-dialogue[530]: INFO:snips_dialogue_hermes: Loading the configuration file
Mar 16 08:22:14 raspberrypi snips-analytics[529]: INFO:snips_analytics_hermes: The analytics service is temporarily disabled
Mar 16 08:22:14 raspberrypi snips-audio-server[527]: INFO:snips_broadcast_mqtt_server: Starting broadcasting audio on hermes as site "default"
Mar 16 08:22:14 raspberrypi snips-skill-server[523]: INFO:snips_skill_server_lib::runner: found action "/var/lib/snips/skills/snips_homematic_xml/action-getState-Homematic.py"
Mar 16 08:22:14 raspberrypi snips-skill-server[523]: INFO:snips_skill_server_lib::runner: found action "/var/lib/snips/skills/snips_homematic_xml/action-renewCache-Homematic.py"
Mar 16 08:22:14 raspberrypi snips-skill-server[523]: INFO:snips_skill_server_lib::runner: found action "/var/lib/snips/skills/snips_homematic_xml/action-setOnOff-Homematic.py"
Mar 16 08:22:14 raspberrypi snips-skill-server[523]: INFO:snips_skill_server_lib::runner: found action "/var/lib/snips/skills/snips_homematic_xml/action-setValue-Homematic.py"
Mar 16 08:22:14 raspberrypi snips-skill-server[523]: INFO:snips_skill_server_lib::runner: searching dir for actions: /var/lib/snips/skills/.cache

> Mar 16 08:24:29 raspberrypi snips-skill-server[523]: INFO:snips_skill_server_lib::runner: [renewCache-Homematic][err] Traceback (most recent call last):
Mar 16 08:24:29 raspberrypi snips-skill-server[523]: INFO:snips_skill_server_lib::runner: [renewCache-Homematic][err]   File "_ctypes/callbacks.c", line 234, in 'calling callback function'
Mar 16 08:24:29 raspberrypi snips-skill-server[523]: INFO:snips_skill_server_lib::runner: [renewCache-Homematic][err]   File "/var/lib/snips/skills/snips_homematic_xml/venv/lib/python3.5/site-packages/hermes_python/ffi/wrappers.py", line 61, in convert_arguments_when_invoking_function
Mar 16 08:24:29 raspberrypi snips-skill-server[523]: INFO:snips_skill_server_lib::runner: [renewCache-Homematic][err]     return func(hermes_client, *parsed_args)
Mar 16 08:24:29 raspberrypi snips-skill-server[523]: INFO:snips_skill_server_lib::runner: [renewCache-Homematic][err]   File "./action-renewCache-Homematic.py", line 30, in subscribe_intent_callback
Mar 16 08:24:29 raspberrypi snips-skill-server[523]: INFO:snips_skill_server_lib::runner: [renewCache-Homematic][err]     action_wrapper(hermes, intentMessage, conf)
Mar 16 08:24:29 raspberrypi snips-skill-server[523]: INFO:snips_skill_server_lib::runner: [renewCache-Homematic][err]   File "./action-renewCache-Homematic.py", line 41, in action_wrapper
Mar 16 08:24:29 raspberrypi snips-skill-server[523]: INFO:snips_skill_server_lib::runner: [renewCache-Homematic][err]     dl = common.retrieveDeviceList(url)
Mar 16 08:24:29 raspberrypi snips-skill-server[523]: INFO:snips_skill_server_lib::runner: [renewCache-Homematic][err] NameError: name 'url' is not defined

**Comment by andynoack** [comment]
Super, damit habe ich einen kleinen Bug gefunden! Ist es jetzt besser?

**Comment by vore** [comment]
Ja, jetzt sieht es gut aus! Cache.txt ist angelegt, Geräte sind drin. Ich teste.
