### ISSUE TITLE
statelist Thermostat

### ISSUE THREAD

**Issue by Juergen015** [andynoack/snips_homematic_xml#2]
<device name="Thermostat Wohnzimmer" ise_id="2087" unreach="false" sticky_unreach="false" config_pending="false"><channel name="Thermostat Wohnzimmer:0" ise_id="2088" index="0" visible="" operate=""><datapoint name="BidCos-RF.NEQ1805187:0.UNREACH" type="UNREACH" ise_id="2109" value="false" valuetype="2" valueunit="" timestamp="1554313002" operations="5"/><datapoint name="BidCos-RF.NEQ1805187:0.STICKY_UNREACH" type="STICKY_UNREACH" ise_id="2105" value="false" valuetype="2" valueunit="" timestamp="1554313002" operations="7"/><datapoint name="BidCos-RF.NEQ1805187:0.CONFIG_PENDING" type="CONFIG_PENDING" ise_id="2090" value="false" valuetype="2" valueunit="" timestamp="1554313002" operations="5"/><datapoint name="BidCos-RF.NEQ1805187:0.LOWBAT" type="LOWBAT" ise_id="2099" value="false" valuetype="2" valueunit="" timestamp="1554313002" operations="5"/><datapoint name="BidCos-RF.NEQ1805187:0.RSSI_DEVICE" type="RSSI_DEVICE" ise_id="2103" value="202" valuetype="8" valueunit="" timestamp="1554313002" operations="5"/><datapoint name="BidCos-RF.NEQ1805187:0.RSSI_PEER" type="RSSI_PEER" ise_id="2104" value="205" valuetype="8" valueunit="" timestamp="1554313002" operations="5"/><datapoint name="BidCos-RF.NEQ1805187:0.DEVICE_IN_BOOTLOADER" type="DEVICE_IN_BOOTLOADER" ise_id="2094" value="false" valuetype="2" valueunit="" timestamp="1554313002" operations="5"/><datapoint name="BidCos-RF.NEQ1805187:0.UPDATE_PENDING" type="UPDATE_PENDING" ise_id="2113" value="false" valuetype="2" valueunit="" timestamp="1554313002" operations="5"/></channel><channel name="Thermostat Wohnzimmer Temperatur u. Luftfeuchtigkeit" ise_id="2117" index="1" visible="true" operate="true"><datapoint name="BidCos-RF.NEQ1805187:1.TEMPERATURE" type="TEMPERATURE" ise_id="2119" value="22.400000" valuetype="4" valueunit="°C" timestamp="1555405149" operations="5"/><datapoint name="BidCos-RF.NEQ1805187:1.HUMIDITY" type="HUMIDITY" ise_id="2118" value="35" valuetype="16" valueunit="%" timestamp="1555405149" operations="5"/></channel><channel name="Thermostat Wohnzimmer Heizungsthermostat" ise_id="2120" index="2" visible="true" operate="true"><datapoint name="BidCos-RF.NEQ1805187:2.CONTROL_MODE" type="CONTROL_MODE" ise_id="2129" value="1" valuetype="16" valueunit="" timestamp="1555404792" operations="5"/><datapoint name="BidCos-RF.NEQ1805187:2.LOWBAT_REPORTING" type="LOWBAT_REPORTING" ise_id="2130" value="false" valuetype="2" valueunit="" timestamp="1555404792" operations="5"/><datapoint name="BidCos-RF.NEQ1805187:2.COMMUNICATION_REPORTING" type="COMMUNICATION_REPORTING" ise_id="2128" value="false" valuetype="2" valueunit="" timestamp="1555404792" operations="5"/><datapoint name="BidCos-RF.NEQ1805187:2.WINDOW_OPEN_REPORTING" type="WINDOW_OPEN_REPORTING" ise_id="2144" value="false" valuetype="2" valueunit="" timestamp="1555404792" operations="5"/><datapoint name="BidCos-RF.NEQ1805187:2.BATTERY_STATE" type="BATTERY_STATE" ise_id="2124" value="2.700000" valuetype="4" valueunit="V" timestamp="1555404792" operations="5"/><datapoint name="BidCos-RF.NEQ1805187:2.BOOST_STATE" type="BOOST_STATE" ise_id="2126" value="0" valuetype="16" valueunit="min" timestamp="1555404792" operations="5"/><datapoint name="BidCos-RF.NEQ1805187:2.ACTUAL_TEMPERATURE" type="ACTUAL_TEMPERATURE" ise_id="2122" value="22.400000" valuetype="4" valueunit="°C" timestamp="1555405129" operations="5"/><datapoint name="BidCos-RF.NEQ1805187:2.ACTUAL_HUMIDITY" type="ACTUAL_HUMIDITY" ise_id="2121" value="35.000000" valuetype="4" valueunit="%" timestamp="1555405129" operations="5"/><datapoint name="BidCos-RF.NEQ1805187:2.SET_TEMPERATURE" type="SET_TEMPERATURE" ise_id="2143" value="21.000000" valuetype="4" valueunit="°C" timestamp="1555405129" operations="7"/><datapoint name="BidCos-RF.NEQ1805187:2.AUTO_MODE" type="AUTO_MODE" ise_id="2123" value="" valuetype="2" valueunit="" timestamp="0" operations="2"/><datapoint name="BidCos-RF.NEQ1805187:2.MANU_MODE" type="MANU_MODE" ise_id="2132" value="" valuetype="4" valueunit="°C" timestamp="0" operations="2"/><datapoint name="BidCos-RF.NEQ1805187:2.BOOST_MODE" type="BOOST_MODE" ise_id="2125" value="" valuetype="2" valueunit="" timestamp="0" operations="2"/><datapoint name="BidCos-RF.NEQ1805187:2.COMFORT_MODE" type="COMFORT_MODE" ise_id="2127" value="" valuetype="2" valueunit="" timestamp="0" operations="2"/><datapoint name="BidCos-RF.NEQ1805187:2.LOWERING_MODE" type="LOWERING_MODE" ise_id="2131" value="" valuetype="2" valueunit="" timestamp="0" operations="2"/><datapoint name="BidCos-RF.NEQ1805187:2.PARTY_MODE_SUBMIT" type="PARTY_MODE_SUBMIT" ise_id="2133" value="" valuetype="20" valueunit="" timestamp="0" operations="2"/><datapoint name="BidCos-RF.NEQ1805187:2.PARTY_TEMPERATURE" type="PARTY_TEMPERATURE" ise_id="2142" value="5.000000" valuetype="4" valueunit="°C" timestamp="1555404792" operations="3"/><datapoint name="BidCos-RF.NEQ1805187:2.PARTY_START_TIME" type="PARTY_START_TIME" ise_id="2136" value="0" valuetype="16" valueunit="minutes" timestamp="1555404792" operations="3"/><datapoint name="BidCos-RF.NEQ1805187:2.PARTY_START_DAY" type="PARTY_START_DAY" ise_id="2134" value="1" valuetype="16" valueunit="day" timestamp="1555404792" operations="3"/><datapoint name="BidCos-RF.NEQ1805187:2.PARTY_START_MONTH" type="PARTY_START_MONTH" ise_id="2135" value="1" valuetype="16" valueunit="month" timestamp="1555404792" operations="3"/><datapoint name="BidCos-RF.NEQ1805187:2.PARTY_START_YEAR" type="PARTY_START_YEAR" ise_id="2137" value="0" valuetype="16" valueunit="year" timestamp="1555404792" operations="3"/><datapoint name="BidCos-RF.NEQ1805187:2.PARTY_STOP_TIME" type="PARTY_STOP_TIME" ise_id="2140" value="0" valuetype="16" valueunit="minutes" timestamp="1555404792" operations="3"/><datapoint name="BidCos-RF.NEQ1805187:2.PARTY_STOP_DAY" type="PARTY_STOP_DAY" ise_id="2138" value="1" valuetype="16" valueunit="day" timestamp="1555404792" operations="3"/><datapoint name="BidCos-RF.NEQ1805187:2.PARTY_STOP_MONTH" type="PARTY_STOP_MONTH" ise_id="2139" value="1" valuetype="16" valueunit="month" timestamp="1555404792" operations="3"/><datapoint name="BidCos-RF.NEQ1805187:2.PARTY_STOP_YEAR" type="PARTY_STOP_YEAR" ise_id="2141" value="0" valuetype="16" valueunit="year" timestamp="1555404792" operations="3"/>

**Comment by Juergen015** [comment]
hat glaube nicht wirklich funktioniert mit meinem ersten Issue

**Comment by andynoack** [comment]
Der Text fehlt irgendwie ;)

**Comment by Juergen015** [comment]
na also, endlich...musste erst rausfinden wie ich den Code einfügen kann
`<device name="Thermostat Wohnzimmer" ise_id="2087" unreach="false" sticky_unreach="false" config_pending="false"><channel name="Thermostat Wohnzimmer:0" ise_id="2088" index="0" visible="" operate=""><datapoint name="BidCos-RF.NEQ1805187:0.UNREACH" type="UNREACH" ise_id="2109" value="false" valuetype="2" valueunit="" timestamp="1554313002" operations="5"/><datapoint name="BidCos-RF.NEQ1805187:0.STICKY_UNREACH" type="STICKY_UNREACH" ise_id="2105" value="false" valuetype="2" valueunit="" timestamp="1554313002" operations="7"/><datapoint name="BidCos-RF.NEQ1805187:0.CONFIG_PENDING" type="CONFIG_PENDING" ise_id="2090" value="false" valuetype="2" valueunit="" timestamp="1554313002" operations="5"/><datapoint name="BidCos-RF.NEQ1805187:0.LOWBAT" type="LOWBAT" ise_id="2099" value="false" valuetype="2" valueunit="" timestamp="1554313002" operations="5"/><datapoint name="BidCos-RF.NEQ1805187:0.RSSI_DEVICE" type="RSSI_DEVICE" ise_id="2103" value="202" valuetype="8" valueunit="" timestamp="1554313002" operations="5"/><datapoint name="BidCos-RF.NEQ1805187:0.RSSI_PEER" type="RSSI_PEER" ise_id="2104" value="205" valuetype="8" valueunit="" timestamp="1554313002" operations="5"/><datapoint name="BidCos-RF.NEQ1805187:0.DEVICE_IN_BOOTLOADER" type="DEVICE_IN_BOOTLOADER" ise_id="2094" value="false" valuetype="2" valueunit="" timestamp="1554313002" operations="5"/><datapoint name="BidCos-RF.NEQ1805187:0.UPDATE_PENDING" type="UPDATE_PENDING" ise_id="2113" value="false" valuetype="2" valueunit="" timestamp="1554313002" operations="5"/></channel><channel name="Thermostat Wohnzimmer Temperatur u. Luftfeuchtigkeit" ise_id="2117" index="1" visible="true" operate="true"><datapoint name="BidCos-RF.NEQ1805187:1.TEMPERATURE" type="TEMPERATURE" ise_id="2119" value="22.400000" valuetype="4" valueunit="°C" timestamp="1555405149" operations="5"/><datapoint name="BidCos-RF.NEQ1805187:1.HUMIDITY" type="HUMIDITY" ise_id="2118" value="35" valuetype="16" valueunit="%" timestamp="1555405149" operations="5"/></channel><channel name="Thermostat Wohnzimmer Heizungsthermostat" ise_id="2120" index="2" visible="true" operate="true"><datapoint name="BidCos-RF.NEQ1805187:2.CONTROL_MODE" type="CONTROL_MODE" ise_id="2129" value="1" valuetype="16" valueunit="" timestamp="1555404792" operations="5"/><datapoint name="BidCos-RF.NEQ1805187:2.LOWBAT_REPORTING" type="LOWBAT_REPORTING" ise_id="2130" value="false" valuetype="2" valueunit="" timestamp="1555404792" operations="5"/><datapoint name="BidCos-RF.NEQ1805187:2.COMMUNICATION_REPORTING" type="COMMUNICATION_REPORTING" ise_id="2128" value="false" valuetype="2" valueunit="" timestamp="1555404792" operations="5"/><datapoint name="BidCos-RF.NEQ1805187:2.WINDOW_OPEN_REPORTING" type="WINDOW_OPEN_REPORTING" ise_id="2144" value="false" valuetype="2" valueunit="" timestamp="1555404792" operations="5"/><datapoint name="BidCos-RF.NEQ1805187:2.BATTERY_STATE" type="BATTERY_STATE" ise_id="2124" value="2.700000" valuetype="4" valueunit="V" timestamp="1555404792" operations="5"/><datapoint name="BidCos-RF.NEQ1805187:2.BOOST_STATE" type="BOOST_STATE" ise_id="2126" value="0" valuetype="16" valueunit="min" timestamp="1555404792" operations="5"/><datapoint name="BidCos-RF.NEQ1805187:2.ACTUAL_TEMPERATURE" type="ACTUAL_TEMPERATURE" ise_id="2122" value="22.400000" valuetype="4" valueunit="°C" timestamp="1555405129" operations="5"/><datapoint name="BidCos-RF.NEQ1805187:2.ACTUAL_HUMIDITY" type="ACTUAL_HUMIDITY" ise_id="2121" value="35.000000" valuetype="4" valueunit="%" timestamp="1555405129" operations="5"/><datapoint name="BidCos-RF.NEQ1805187:2.SET_TEMPERATURE" type="SET_TEMPERATURE" ise_id="2143" value="21.000000" valuetype="4" valueunit="°C" timestamp="1555405129" operations="7"/><datapoint name="BidCos-RF.NEQ1805187:2.AUTO_MODE" type="AUTO_MODE" ise_id="2123" value="" valuetype="2" valueunit="" timestamp="0" operations="2"/><datapoint name="BidCos-RF.NEQ1805187:2.MANU_MODE" type="MANU_MODE" ise_id="2132" value="" valuetype="4" valueunit="°C" timestamp="0" operations="2"/><datapoint name="BidCos-RF.NEQ1805187:2.BOOST_MODE" type="BOOST_MODE" ise_id="2125" value="" valuetype="2" valueunit="" timestamp="0" operations="2"/><datapoint name="BidCos-RF.NEQ1805187:2.COMFORT_MODE" type="COMFORT_MODE" ise_id="2127" value="" valuetype="2" valueunit="" timestamp="0" operations="2"/><datapoint name="BidCos-RF.NEQ1805187:2.LOWERING_MODE" type="LOWERING_MODE" ise_id="2131" value="" valuetype="2" valueunit="" timestamp="0" operations="2"/><datapoint name="BidCos-RF.NEQ1805187:2.PARTY_MODE_SUBMIT" type="PARTY_MODE_SUBMIT" ise_id="2133" value="" valuetype="20" valueunit="" timestamp="0" operations="2"/><datapoint name="BidCos-RF.NEQ1805187:2.PARTY_TEMPERATURE" type="PARTY_TEMPERATURE" ise_id="2142" value="5.000000" valuetype="4" valueunit="°C" timestamp="1555404792" operations="3"/><datapoint name="BidCos-RF.NEQ1805187:2.PARTY_START_TIME" type="PARTY_START_TIME" ise_id="2136" value="0" valuetype="16" valueunit="minutes" timestamp="1555404792" operations="3"/><datapoint name="BidCos-RF.NEQ1805187:2.PARTY_START_DAY" type="PARTY_START_DAY" ise_id="2134" value="1" valuetype="16" valueunit="day" timestamp="1555404792" operations="3"/><datapoint name="BidCos-RF.NEQ1805187:2.PARTY_START_MONTH" type="PARTY_START_MONTH" ise_id="2135" value="1" valuetype="16" valueunit="month" timestamp="1555404792" operations="3"/><datapoint name="BidCos-RF.NEQ1805187:2.PARTY_START_YEAR" type="PARTY_START_YEAR" ise_id="2137" value="0" valuetype="16" valueunit="year" timestamp="1555404792" operations="3"/><datapoint name="BidCos-RF.NEQ1805187:2.PARTY_STOP_TIME" type="PARTY_STOP_TIME" ise_id="2140" value="0" valuetype="16" valueunit="minutes" timestamp="1555404792" operations="3"/><datapoint name="BidCos-RF.NEQ1805187:2.PARTY_STOP_DAY" type="PARTY_STOP_DAY" ise_id="2138" value="1" valuetype="16" valueunit="day" timestamp="1555404792" operations="3"/><datapoint name="BidCos-RF.NEQ1805187:2.PARTY_STOP_MONTH" type="PARTY_STOP_MONTH" ise_id="2139" value="1" valuetype="16" valueunit="month" timestamp="1555404792" operations="3"/><datapoint name="BidCos-RF.NEQ1805187:2.PARTY_STOP_YEAR" type="PARTY_STOP_YEAR" ise_id="2141" value="0" valuetype="16" valueunit="year" timestamp="1555404792" operations="3"/>`

**Comment by Juergen015** [comment]
eine Kleinigkeit habe ich noch im SetValue-Script gefunden, und geändert..
`    try:
        spoken_name = str(intentMessage.slots.Device.first().value).lower()
        spoken_percent = intentMessage.slots.Prozentwert.first().value/100
        wert = spoken_percent*100
        if common.changeDeviceState(url, common.getID(dl, spoken_name), spoken_percent):
            if verbose == 'True' or verbose == 'true':
                result_sentence = "Ok, Ich setze " + spoken_name + " auf " + str(wert) + " Prozent." 
`
Die Variable (wert) gibt jetzt den richtigen % wert aus..., nur so eine Idee.
Ich muss dazu sagen, ich kenne mich mit Python nicht aus. Ich schreibe so aus Vergnügen Programme mit Delphi

**Comment by andynoack** [comment]
Ich habe beides jetzt einmal angepasst.

**Comment by Juergen015** [comment]
Ich habe es mal getestet, die Statusabfrage funktioniert bei dem Thermostat noch nicht. Es kommt die Meldung das der Zustand an oder aus ist, nicht die Gradzahl. Alles andere ist soweit gut. Es müsste zwar keine nachkomma-stelle gesprochen werden aber es ist ok

**Comment by andynoack** [comment]
Ich habe eine Idee für eine Änderung, möchte es aber nicht im Hauptcode ändern:
Zeile 114 in common.py:
if pair[0] == 'name' and 'STATE' in pair[1]: ändern in:
if pair[0] == 'name' and 'STATE' == pair[1]:

Eventuell löst das das Problem mit der Sprachausgabe. Bitte Feedback :)

**Comment by Juergen015** [comment]
Hallo, geht leider nicht. Ich bekomme zwar als Antwort nicht mehr das der Status an oder aus ist, sondern jetzt die Gradzahl die aber dann nicht stimmt. Und bei einem Schaltaktor auch jetzt die Gradzahl.

**Comment by Juergen015** [comment]
Auch das Auslesen der CCU ist nicht richtig. Ich ändere immer die Einträge manuell.

**Comment by Juergen015** [comment]
Ich habe mir mit Delphi eine Haussteuerung gebastelt die ID's sind in einer INI Datei hinterlegt.. 
kleines Beispiel:
SchaltaktorXY- ID: 1796 um das Gerät zu steuern.. und 1800 um den Status abzufragen.
ThermostatXY-ID: 2143 um das Gerät zu steuern(Soll Temp.).. 2143 Status (Soll Temp),..2122 Status (Aktuelle Temp) 
DimmerXY-ID: 3354 um das Gerät zu steuern.. und 3370 um den Status abzufragen.

**Comment by andynoack** [comment]
Die Steuerung der Geräte (Auswahl der ise_id) funktioniert bei mir, ich habe nur keine steuerbaren Thermostate zuhause. Status von Rollladen/Dimmer in Prozent auslesen habe ich gerade getestet und funktioniert auch. Eventuell hilft mir der vollständige XML-Dump, offensichtlich ist es irgendwie anders konfiguriert.

**Comment by Juergen015** [comment]
Ich habe eigendlich nichts groß konfiguriert, die StateList oben ist komplett für ein Thermostat

**Comment by andynoack** [comment]
Ich suche darin nach den Schlüsselwörtern (z.B. STATE), ob die in ähnlicher Form auftauchen. Ist das der Fall, kann der Algorithmus falsch abbiegen. Mir würde auch eine Ausgabe reichen, bei der alle Zeilen mit STATE enthalten sind (cat dump.xml | grep -i state).

**Comment by Juergen015** [comment]
oha, jtzt blicke ich nix mehr :-)

**Comment by andynoack** [comment]
...oder einfach den vollständigen Dump (aus dem mich nur bestimmte Dinge interessieren)

**Comment by Juergen015** [comment]
ich habe keine Ahnung was ich jetzt machen soll

**Comment by andynoack** [comment]
So wie oben die statelist.cgi-Ausgabe eintragen, nur eben alles, damit ich nachvollziehen kann, warum er wo falsch abbiegt. Außerdem würde mir noch einmal eine ganz präzise Formulierung helfen, was genau nicht funktioniert.

**Comment by Juergen015** [comment]
in der Liste oben ist doch schon alles für ein Thermostat

**Comment by andynoack** [comment]
Ja, aber in dem Ausschnitt kann ich kein Problem erkennen.

**Comment by Juergen015** [comment]
was anderes kann ich leider nicht anbieten, das wird mir bei statelist ausgegeben

**Comment by andynoack** [comment]
Ich würde z.B. die Dimmer-Ausgabe mit meiner vergleichen und gucken, warum es nicht geht...(bei mir funktioniert es ja)

**Comment by Juergen015** [comment]
kleines Beispiel beim Automatischem Aktualisieren:
Device,2081,heizung wohnzimmer
richtig wäre es aber mit der ID 2143

**Comment by Juergen015** [comment]
Die Dimmer und Schaltaktoren sind OK. nur mit dem Thermostat geht es nicht...zumindest mit dem alten Script ohne die neue Änderung

**Comment by andynoack** [comment]
Was geht denn nicht? Setzen oder auslesen?

**Comment by Juergen015** [comment]
Also kurze Zusammenfassung:
- Dimmer, Schaltaktoren --- Status - OK., setValue - OK, set OnOff - OK,, Neu einlesen OK.
- Thermostat --- Status - Nein, kommt die Meldung ( an oder aus), setValue OK nach änderung der ID.

**Comment by andynoack** [comment]
Nur, um das zu bestätigen: Zum Auslesen der Temperatur (2119) benötigt man eine andere ise_id als zum Setzen (2143). Wenn das so ist, muss ich im System nicht unerheblich was ändern.

**Comment by Juergen015** [comment]
2119 oder 2122 zum auslesen der aktuellen Temperatur
2143 zum setzen der Soll Temperatur

**Comment by Juergen015** [comment]
gibt es schon neuigkeiten?

**Comment by andynoack** [comment]
Ich bin bisher leider noch nicht dazu gekommen, denn der Umbau wird ein bisschen größer werden.

**Comment by Juergen015** [comment]
ok...kein problem :-)

**Comment by andynoack** [comment]
Ich habe gerade ein bisschen Zeit gehabt und implementiert. Funktioniert es nun?

**Comment by Juergen015** [comment]
Leider nicht, die ID's werden falsch ausgelesen und teilweise auch garnicht. Dadurch natürlich auch keine funktion beim setzten der Temperatur oder Statusabfrage

**Comment by Juergen015** [comment]
oha, die ist riesengroß, und mit einfach kopieren/einfügen funktioniert das hier nicht wegen dem xml-code

**Comment by Juergen015** [comment]
ich könnte die Liste per mail schicken, ist das ok?

**Comment by andynoack** [comment]
Ja, einfach senden.

**Comment by andynoack** [comment]
Ok, dann brauch ich einmal den Output von statelist.cgi und die cache.txt, damit ich schauen kann, wo er warum falsch ausgelesen hat.

**Comment by Juergen015** [comment]
ok, mail ist raus

**Comment by andynoack** [comment]
Ich habe gerade gepatched und mit den angegebenen Daten geprüft. Es sollte jetzt besser funktionieren! 

Anmerkung: Die IDs weichen leicht ab, da ich nicht den Parent sondern eine bestimmte Child-ID nutze. Außerdem war die Namensgebung im zugesendeten XML-File noch nicht optimal, es sind viel zu viele Namen gesetzt, die aber in der Praxis vermutlich nicht genutzt werden. Da würde ich entsprechend in der CCU noch einmal anpassen.

**Comment by Juergen015** [comment]
Ich habe es gerade getestet, geht leider nicht

**Comment by andynoack** [comment]
Die IDs passen nicht?

**Comment by Juergen015** [comment]
die ID's beim auslesen, und dann natürlich die Abfrage nicht

**Comment by andynoack** [comment]
Wie sieht die cache.txt aus und wie sollte es sein?

**Comment by Juergen015** [comment]
Device,1013,ccu
Device,3370,licht 1
Device,2356,licht 2
Device,2454,licht 3
Device,1710,licht 4
Device,1850,relais 4
Device,2791,schaltaktor heizung schlafzimmer frequnz-sensor
Device,2664,schaltaktor heizung badezimmer frequnz-sensor
Device,2085,heizung wohnzimmer
Device,1800,terrasse
Device,2751,thermostat badezimmer schaltaktor
Device,2877,thermostat schlafzimmer schaltaktor
Device,2143,thermostat wohnzimmer schaltaktor
Device,3424,wandtaster licht 3 an
Program,2244,gute nacht
Program,5124,guten abend
Program,3957,guten morgen
Program,5026,kino beleuchtung
Program,3891,licht
Program,3935,rolladen auf
Program,3901,rolladen zu
Program,4282,rollos prufen
so wurde der Cache ausgelesen

**Comment by Juergen015** [comment]
Device,3354,licht 1
Device,2340,licht 2
Device,2438,licht 3
Device,1694,licht 4
Device,1796,terrasse
Device,2143,heizung wohnzimmer
Device,2751,heizung badezimmer
Device,2877,heizung schlafzimmer
Program,3957,guten morgen
Program,5124,guten abend
Program,2244,gute nacht
Program,3935,rolladen auf
Program,3901,rolladen zu
Program,3891,licht
Program,5026,kino beleuchtung
so müsste es sein

**Comment by andynoack** [comment]
Passt doch...Die Geräte haben nur andere Namen, aber die werden so aus der CCU ausgelesen...

**Comment by Juergen015** [comment]
Beispiel Thermostat Wohnzimmer... zum stellen ID 2143, zum abfragen ID 2122

**Comment by andynoack** [comment]
Es ist so implementiert, dass er die ID für das Abfragen nicht speichern muss. Da reicht der richtige Name. Ich würde "thermostat wohnzimmer schaltaktor" in "Thermostat Wohnzimmer" umbenennen und die restlichen Klartextnamen in der CCU (die, die man nicht braucht) zurücksetzen.
Der Algorithmus kann nur funktionieren, wenn die Namen richtig eingestellt sind. Es geht ja um Spracherkennung, deswegen kann ich in dem Punkt leider nicht mehr Flexibilität anbieten.

**Comment by Juergen015** [comment]
ok, versuche ich mal

**Comment by Juergen015** [comment]
geht nicht

**Comment by andynoack** [comment]
Wie sieht das Ergebnis aus?

**Comment by Juergen015** [comment]
licht stellen und status ok, heizung stellen ok, Heizung status kommt die Meldung ist an oder aus

**Comment by andynoack** [comment]
OK, also die IDs passen, aber er findet für die Status-Ausgabe nicht den richtigen Node oder wählt die falsche Formulierung. Das muss ich bei mir Mal mit der XML-File aus der E-Mail im Trockenen testen.
Vielleicht nochmal probieren, das ggf. zweite vorhandene Wohnzimmer-Device bei der Statusabfrage zu nennen.

**Comment by Juergen015** [comment]
ok, ich teste auch noch etwas

**Comment by Juergen015** [comment]
wenn ich einen Befehl spreche, was wird denn dann gesucht bzw. im Programm abgefragt?

**Comment by Juergen015** [comment]
vieleicht muss ich ja nur die ID's manuell abändern

**Comment by andynoack** [comment]
Er sucht unterhalb des genannten Knotens im XML-File den STATE-Wert

**Comment by Juergen015** [comment]
und beim Setzen?

**Comment by andynoack** [comment]
IDs würde ich nicht manuell ändern. Wenn ich die aktuelle statelist mit den jetzt neuen Namen per Mail bekomme, schaue ich gleich Mal rein, was er da genau ausliest.

**Comment by andynoack** [comment]
Beim setzen muss die ID passen, da wird die aus der cache.txt genommen.

**Comment by Juergen015** [comment]
ich wollte eigendlich nichts in der CCU abändern

**Comment by andynoack** [comment]
Ich kann aber nur mit dem arbeiten, was ich von dort bekomme. Wenn die Namen nicht passen, stehen die Chancen schlecht, dass es sauber funktioniert

**Comment by Juergen015** [comment]
die Namen in der CCU sind eigendlich richtig, ich werde mal ein paar Bilder mitschicken

**Comment by andynoack** [comment]
Nicht notwendig, das steht ja alles schwarz auf weiss in der statelist-XML...die lügt nicht ;)

**Comment by Juergen015** [comment]
ok. :-))

**Comment by Juergen015** [comment]
in meinem Windows Prog. habe ich es anders gelöst

**Comment by andynoack** [comment]
Habe es nun nochmal angepasst...ist das Ergebnis nun anders?

**Comment by Juergen015** [comment]
Device,1013,ccu
Device,3370,licht 1
Device,2356,licht 2
Device,2454,licht 3
Device,1710,licht 4
Device,1832,relais 1
Device,2791,schaltaktor heizung schlafzimmer schaltaktor
Device,2664,schaltaktor heizung badezimmer schaltaktor
Device,2085,heizung wohnzimmer
Device,1800,terrasse
Device,2751,thermostat badezimmer heizungsthermostat
Device,2877,thermostat schlafzimmer heizungsthermostat
Device,2143,thermostat wohnzimmer heizungsthermostat
Device,3424,wandtaster licht 3 an
Program,2244,gute nacht
Program,5124,guten abend
Program,3957,guten morgen
Program,5026,kino beleuchtung
Program,3891,licht
Program,3935,rolladen auf
Program,3901,rolladen zu
Program,4282,rollos prufen
so sieht die cache.txt jetzt aus

**Comment by Juergen015** [comment]
die ID's müssten jetzt stimmen, ich teste es mal

**Comment by Juergen015** [comment]
Licht ist ok..(setzen und Status), beim Thermostat... (setzten ist ok) bei der Statusabfrage kommt die Meldung ( ist an oder aus)

**Comment by Juergen015** [comment]
also wird bei der Statusabfrage der Schaltaktor abgefragt und nicht die Temperatur

**Comment by andynoack** [comment]
Ich denke eher, dass er mit der Namensgebung durcheinander kommt. Wenn die so benannten Schaltaktoren entfernt werden, geht es möglicherweise sofort. Ich konnte bei mir (mit dem XML-Dump) aus der Mail die Temperaturen auslesen, bei Eingabe des richtigen Namens.

**Comment by Juergen015** [comment]
Ich habe jetzt in der CCU die Bezeichnungen geändert...tatsächlich jetzt geht es...
vielen vielen dank
Device,1013,ccu
Device,3370,licht 1
Device,2356,licht 2
Device,2454,licht 3
Device,1710,licht 4
Device,1832,relais 1
Device,2791,schaltaktor heizung schlafzimmer
Device,2664,schaltaktor heizung badezimmer
Device,2085,schaltaktor heizung wohnzimmer
Device,1800,terrasse
Device,2751,heizung badezimmer
Device,2877,heizung schlafzimmer
Device,2143,heizung wohnzimmer
Device,3424,wandtaster licht 3 an
Program,2244,gute nacht
Program,5124,guten abend
Program,3957,guten morgen
Program,5026,kino beleuchtung
Program,3891,licht
Program,3935,rolladen auf
Program,3901,rolladen zu
Program,4282,rollos prufen

**Comment by andynoack** [comment]
Sehr schön! Das freut mich, dann mache ich den Issue zu.
