### ISSUE TITLE
Geräte mit mehreren Kanälen werden in der cache.txt nicht vollständig angelegt

### ISSUE THREAD

**Issue by kmbach** [andynoack/snips_homematic_xml#5]
Hallo,

ich habe hier ein Gerät welches mehrere Kanäle hat. Es handelt sich dabei um die Relaisbox 
HM-LC-Sw4-WM. Um alle vier Kanäle in die cache.txt zu bekommen mußte ich in der Funktion `common.retrieveDeviceList()` die `devicelist.append([save_name, save_ise_id])`  vom Ende der Funktion in die Schleife:
`for pair in datapoint.items():`
unter:
`if pair[0] == 'ise_id' and usethisdatapoint:  `
verlegen.
Auf diese Art werden z.B. CUxD Geräte mit mehreren Kanälen nutzbar.

Gruß kmbach

**Comment by andynoack** [comment]
Hi! Sorry erst einmal für die späte Antwort, meine Notification war aus. Ich schaue mir das die Tage einmal an, will es aber erst testen, bevor ich es offiziell aufnehme.
