### ISSUE TITLE
Nickname in der cache.txt

### ISSUE THREAD

**Issue by kmbach** [andynoack/snips_homematic_xml#6]
Hallo,

ich hatte kürzlich den Wunsch nach nicknames in der cache.txt geäußert. Die devicenames dort zu überschreiben ist zwar eine Lösung, erhöht aber nicht unbedingt die Übersichtlichkeit.  Bei vielen nicknames bleibt als Zuordnung nur die ISE-ID in der cache.txt und die sagt nicht soviel aus wie der devicename. Auch die Datei anschließend mit einem Schreibschutz zu versehen, um diese vor einer unbeabsichtigten Aktualierung zu schützen, bringt so einige Nachteile.
Vielleicht ist diese Lösung ja interessant. Dabei müssen die Beiden Funktionen `common.writecache()` und `common.readcache()` geändert werden.  Den nickname schreibt man dabei zwischen die ISE-ID und den devicenamen. 
`Device,63948,Stehlampe aus,funk433-2.1-aus`
Beim Einlesen der cache.txt wird, soweit vorhanden, der nickname statt des devicename eingelesen. So bleibt die ursprüngliche Datenstruktur unberührt. Beim schreiben der cachte.txt wird zunächst die bestehende cache.txt eingelesen um vorhandene nicknames aus dieser in die neue cache.txt zu übernehmen. 
```
def writecache(devicelist, programlist):
    dl, pl = readcache()
    file = open(CACHE, "w") 

    def l_writecache (file, type, dlist, cl):    
        for i in dlist:
            nickname = 0
            try:   # wenn Datei nicht existiert
                for j in cl:
                    if i[1] == str(j[1]):  # ID vergleichen
                        if i[0].lower() != j[0].lower():   # Name vergleichen, wenn ungleich, dann Nickname vorhanden          
                            nickname = 1
                            file.write(type + "," + str(i[1]) + "," + str(j[0]) + "," + str(i[0]) + "\n")  
                            break
            except:
                pass        
            if not nickname:
                file.write(type + "," + str(i[1]) + "," + str(i[0]) + "\n")  
            
    l_writecache (file, "Device", devicelist, dl)        
    l_writecache (file, "Program", programlist, pl)  
    
    file.close()

```

``` 
def readcache():
    devicelist = []
    programlist = []
    
    try:
        file = open(CACHE, "r")
        for line in file: 
            isnick = 0            
            try:        # devicename, wenn Nickname vorhanden abschneiden
                type, id, name, dummy = line.split(",", 3)
                isnick = 1
            except:
                type, id, name = line.split(",", 2)
                    
            if type == "Device":
                devicelist.append([name.strip("\n"), int(id)])
            if type == "Program":
                programlist.append([name.strip("\n"), int(id)])            
        file.close()
    except:
        pass
    return devicelist, programlist
 ```
Gruß kmbach

**Comment by andynoack** [comment]
Hier bin ich mir unsicher, ob das in die Hauptversion rein soll. Vielleicht tut es ja in diesem Fall auch ein Fork.
